services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
    - my_network
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - my_network
    depends_on:
    - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443"
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - my_network
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ayac/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/ayac/data/mariadb'
  
networks:
  my_network:
    driver: bridge